### ISSUE TITLE
Add rg or other grep tool support

### ISSUE THREAD

**Issue by jqhr** [bfrg/vim-fzy#1]
Rg (or ag, ack) is greate grep tool, when I want find some text of files,

**Comment by bfrg** [comment]
I have created branch [fzygrep](https://github.com/bfrg/vim-fzy/tree/fzygrep). Feel free to give it a try and see if that's what you were looking for.

The grep-command can be specified through the entries `g:fzy.grepcmd` and `g:fzy.grepformat`. For example, to use `ripgrep`:
```vim
let g:fzy = {
    'grepcmd': 'rg --vimgrep',
    'grepformat': '%f:%l:%c:%m'
}
```
`ripgrep` options can also be specified on the command line, like `:FzyGrep --smart-case typedef /path/to/main.c`. All arguments passed to `:FzyGrep` are appended to `rg --vimgrep`.
