### ISSUE TITLE
FzyLiveGrep

### ISSUE THREAD

**Issue by haze** [bfrg/vim-fzy#3]
Just wanted to preface this feature request with a thanks. This plugin rocks!

Is it possible to have a live-updating grep view using `fzy` to select candidates?

**Comment by bfrg** [comment]
No, unfortunately this is not possible due to limitations in `fzy`. Other fuzzy searchers, like `fzf` or `skim` support a live-updating grep after every keystroke. I'm afraid there's nothing I can do about it.

**Comment by haze** [comment]
That's unfortunate. I like `fzy` and this plugin enough to adjust my workflow however. Thanks again!
