### ISSUE TITLE
Edit commands are filled into history command after running Fzy* command

### ISSUE THREAD

**Issue by phongnh** [bfrg/vim-fzy#5]
Hi bfrg,

Thanks for your great plugin. I find that the behavior / experience (adding edit command to history after running Fzy* commands) is not unusual for me. History now is filled up with edit command.

Not sure this is a bug or your intent on implementation?

[![asciicast](https://asciinema.org/a/lskapnHqzkyKBSIivByFDle4J.svg)](https://asciinema.org/a/lskapnHqzkyKBSIivByFDle4J)

**Comment by bfrg** [comment]
Yes, this is intentional. But if it bothers you, I could make it optional or even remove it entirely.

**Comment by phongnh** [comment]
@bfrg Thanks for your updates. For me, I don't need history commands from Fzy*. Not sure other users need or not. Could you make it optional? Thanks.

**Comment by bfrg** [comment]
Fixed by #6.
