### ISSUE TITLE
'g:fzy.showinfo' seems to crash the displaying of commands

### ISSUE THREAD

**Issue by saccarosium** [bfrg/vim-fzy#7]
Hi,
I've activate the showinfo configuration option and the fzy terminal wouldn't appear. After some investigation I found that the '--show-info' flag isn't present in fzy anymore.

details
OS: Arch Linux
fzy version: 1.0

**Comment by bfrg** [comment]
I just checked the latest version from Github and the option `--show-info` is still present. IIRC Arch won't install the latest fzy version from Github, only the latest release. This new option was added _after_ the 1.0 release. There's even a 4  year old [issue](https://github.com/jhawthorn/fzy/issues/147) about tagging a new release.

**Comment by saccarosium** [comment]
Thanks that was really confusing
